### ISSUE TITLE
RBAC rules for the tiller pod

### ISSUE THREAD

**Issue by javsalgar** [kubeapps/manifest#20]
After using `kubeapps up` in a `kubeadm` installation (which has RBAC enabled by default), helm is not working because of the following error:

```
Error: no available release name found
```

Tiller logs
```
[tiller] 2017/11/23 12:51:20 info: generated name wrapping-leopard is taken. Searching again.
[storage] 2017/11/23 12:51:20 getting release "loitering-garfish.v1"
[storage/driver] 2017/11/23 12:51:20 get: failed to get "loitering-garfish.v1": configmaps "loitering-garfish.v1" is forbidden: User "system:serviceaccount:kube-system:default" cannot get configmaps in the namespace "kube-system"
[tiller] 2017/11/23 12:51:20 info: generated name loitering-garfish is taken. Searching again.
[storage] 2017/11/23 12:51:20 getting release "prodding-ostrich.v1"
[storage/driver] 2017/11/23 12:51:20 get: failed to get "prodding-ostrich.v1": configmaps "prodding-ostrich.v1" is forbidden: User "system:serviceaccount:kube-system:default" cannot get configmaps in the namespace "kube-system"
[tiller] 2017/11/23 12:51:20 info: generated name prodding-ostrich is taken. Searching again.
[storage] 2017/11/23 12:51:20 getting release "zealous-maltese.v1"
[storage/driver] 2017/11/23 12:51:20 get: failed to get "zealous-maltese.v1": configmaps "zealous-maltese.v1" is forbidden: User "system:serviceaccount:kube-system:default" cannot get configmaps in the namespace "kube-system"
[tiller] 2017/11/23 12:51:20 info: generated name zealous-maltese is taken. Searching again.
[storage] 2017/11/23 12:51:20 getting release "tailored-saola.v1"
[storage/driver] 2017/11/23 12:51:20 get: failed to get "tailored-saola.v1": configmaps "tailored-saola.v1" is forbidden: User "system:serviceaccount:kube-system:default" cannot get configmaps in the namespace "kube-system"
[tiller] 2017/11/23 12:51:20 info: generated name tailored-saola is taken. Searching again.
[tiller] 2017/11/23 12:51:20 warning: No available release names found after 5 tries
[tiller] 2017/11/23 12:51:20 failed install prepare step: no available release name found
```

*Screenshot*

<img width="778" alt="screen shot 2017-11-23 at 13 48 57" src="https://user-images.githubusercontent.com/1133777/33174077-ccbd403e-d056-11e7-8027-6cdad2c0082c.png">

*Steps to reproduce*

 - Spin up a kubeadm cluster
 - Execute kubeapps up 
 - Try to deploy a chart

**Comment by sameersbn** [comment]
FWIW, while using helm on a RBAC cluster I found that you first need to create a service account for helm

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: kube-system
```

save this file as `helm-sa.yaml` and execute `kubectl create -f helm-sa.yaml`. From here you can do ` helm init --service-account helm` and have helm come up properly.
